/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/applications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["applications_list"];
        put?: never;
        post: operations["applications_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_number}/milestones/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["applications_milestones_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{application_number}/milestones/{id}/action/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["applications_milestones_action_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["applications_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/{id}/submit/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["applications_submit_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/status/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["applications_status_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/applications/streams/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["applications_streams_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/{application_number}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["certificates_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/{application_number}/{id}/download/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["certificates_download_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/certificates/{application_number}/{id}/receive-signed/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["certificates_receive_signed_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compliance/audit/{target_type}/{target_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["compliance_audit_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compliance/clearances/{application_number}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["compliance_clearances_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compliance/clearances/{application_number}/create/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["compliance_clearances_create_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compliance/clearances/{id}/fulfill/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["compliance_clearances_fulfill_partial_update"];
        trace?: never;
    };
    "/api/compliance/complaints/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["complaints_list"];
        put?: never;
        post: operations["compliance_complaints_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/compliance/complaints/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["complaints_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["compliance_complaints_partial_update"];
        trace?: never;
    };
    "/api/csrf/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Return a CSRF cookie. React calls this once on mount. */
        get: operations["csrf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/{id}/presigned/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_presigned_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/slots/{milestone_instance_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["documents_slots_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/documents/upload/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["documents_upload_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fees/{application_number}/assessment/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["fees_assessment_retrieve"];
        put?: never;
        post: operations["fees_assessment_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fees/{application_number}/payments/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["fees_payments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fees/{application_number}/payments/{id}/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["fees_payments_verify_partial_update"];
        trace?: never;
    };
    "/api/fees/{application_number}/payments/record/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["fees_payments_record_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fees/estimate/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["fees_estimate_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/healthz/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity/login/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["identity_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity/logout/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["identity_logout_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["identity_me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity/otp/resend/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["identity_otp_resend_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity/otp/verify/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["identity_otp_verify_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/identity/signup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["identity_signup_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/officer/queue/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["officer_queue_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `approve` - approve
         *     * `reject` - reject
         *     * `return_for_correction` - return_for_correction
         * @enum {string}
         */
        ActionEnum: "approve" | "reject" | "return_for_correction";
        ApplicationCreateRequest: {
            stream_id: number;
            /** @default  */
            plpn: string;
            /** Format: decimal */
            plot_area_sqm: string;
            /** Format: decimal */
            proposed_bua_sqm: string;
            /** Format: decimal */
            existing_bua_sqm: string;
            /** Format: decimal */
            zonal_rrr: string;
        };
        ApplicationRead: {
            readonly id: number;
            readonly application_number: string;
            readonly stream_code: string;
            readonly stream_name: string;
            readonly status: components["schemas"]["ApplicationReadStatusEnum"];
            /** Plot/Land Plan Number */
            readonly plpn: string;
            /** Format: decimal */
            readonly plot_area_sqm: string | null;
            /** Format: decimal */
            readonly proposed_bua_sqm: string | null;
            /** Format: decimal */
            readonly existing_bua_sqm: string | null;
            /** Format: decimal */
            readonly zonal_rrr: string | null;
            /** Format: date-time */
            readonly submitted_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `draft` - Draft
         *     * `submitted` - Submitted
         *     * `under_scrutiny` - Under Scrutiny
         *     * `awaiting_next_milestone` - Awaiting Next Milestone
         *     * `rejected` - Rejected
         *     * `approved` - Approved
         *     * `expired` - Expired
         *     * `withdrawn` - Withdrawn
         * @enum {string}
         */
        ApplicationReadStatusEnum: "draft" | "submitted" | "under_scrutiny" | "awaiting_next_milestone" | "rejected" | "approved" | "expired" | "withdrawn";
        AuditEvent: {
            readonly id: number;
            readonly sequence: number | null;
            verb: string;
            target_type: string;
            /** Format: int64 */
            target_id: number;
            actor?: number | null;
            payload?: unknown;
            ip_address?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `aip` - Approval in Principle
         *     * `development_permission` - Development Permission
         *     * `commencement_plinth` - Commencement Certificate to Plinth
         *     * `further_commencement` - Further Commencement Certificate
         *     * `commencement_80pct` - Commencement Certificate (80% BUA)
         *     * `commencement_rem20` - Commencement Certificate (Remaining 20%)
         *     * `building_completion` - Building Completion Certificate
         *     * `oc` - Occupancy Certificate
         *     * `demolition_clearance` - Demolition & Site Clearance Certificate
         * @enum {string}
         */
        CertificateTypeEnum: "aip" | "development_permission" | "commencement_plinth" | "further_commencement" | "commencement_80pct" | "commencement_rem20" | "building_completion" | "oc" | "demolition_clearance";
        /**
         * @description * `railway` - Railway Authority NOC
         *     * `crz` - CRZ / MCZMA Coastal Clearance
         *     * `heritage_mhcc` - MHCC Heritage Clearance
         *     * `aviation_aai` - AAI / Aviation Clearance
         *     * `pollution_mpcb` - MPCB Pollution Control Clearance
         * @enum {string}
         */
        ClearanceTypeEnum: "railway" | "crz" | "heritage_mhcc" | "aviation_aai" | "pollution_mpcb";
        ComplaintCreateRequest: {
            application_id: number;
            subject: string;
            body: string;
        };
        ComplaintRead: {
            readonly id: number;
            application: number;
            origin: components["schemas"]["OriginEnum"];
            raised_by?: number | null;
            subject: string;
            body: string;
            status?: components["schemas"]["ComplaintReadStatusEnum"];
            resolution_notes?: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** Format: date-time */
            resolved_at?: string | null;
        };
        /**
         * @description * `open` - Open
         *     * `in_review` - In Review
         *     * `resolved` - Resolved
         *     * `closed` - Closed
         * @enum {string}
         */
        ComplaintReadStatusEnum: "open" | "in_review" | "resolved" | "closed";
        ConditionalClearanceCreateRequest: {
            milestone_instance_id?: number | null;
            clearance_type: components["schemas"]["ClearanceTypeEnum"];
            description: string;
            trigger_metadata?: unknown;
        };
        ConditionalClearanceRead: {
            readonly id: number;
            application: number;
            milestone_instance?: number | null;
            clearance_type: components["schemas"]["ClearanceTypeEnum"];
            description: string;
            trigger_metadata?: unknown;
            clearance_doc?: number | null;
            is_fulfilled?: boolean;
            /** Format: date-time */
            fulfilled_at?: string | null;
            fulfilled_by?: number | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        CsrfResponse: {
            csrfToken: string;
        };
        /**
         * @description * `verified` - verified
         *     * `rejected` - rejected
         *     * `mismatch` - mismatch
         * @enum {string}
         */
        DecisionEnum: "verified" | "rejected" | "mismatch";
        DocumentSlotRead: {
            readonly id: number;
            readonly stream_code: string;
            readonly milestone_code: string;
            document_type: string;
            is_mandatory?: boolean;
            applies_when?: string;
        };
        DocumentUploadCreateRequest: {
            /** Format: binary */
            file: string;
            document_slot_id?: number | null;
            milestone_instance_id?: number | null;
        };
        DocumentUploadRead: {
            readonly id: number;
            readonly application_number: string;
            /** Format: int64 */
            version?: number;
            original_filename: string;
            content_type: string;
            /** Format: int64 */
            size_bytes: number;
            /** Format: date-time */
            readonly uploaded_at: string;
            readonly presigned_url: string;
        };
        DownloadUrlResponse: {
            /** Format: uri */
            url: string;
        };
        FeeAssessmentRead: {
            readonly id: number;
            /** Format: decimal */
            scrutiny_fee: string;
            /** Format: decimal */
            security_deposit: string;
            /** Format: decimal */
            debris_deposit: string;
            /** Format: decimal */
            premium_total?: string;
            /** Format: decimal */
            total_amount: string;
            /** Format: date-time */
            readonly assessed_at: string;
            /** Format: decimal */
            bua_sqm_snapshot: string;
            /** Format: decimal */
            zonal_rrr_snapshot: string;
            is_current?: boolean;
            is_locked?: boolean;
            /** Format: date-time */
            locked_at?: string | null;
        };
        FeeEstimateResponse: {
            /** Format: decimal */
            scrutiny_fee: string;
            /** Format: decimal */
            security_deposit: string;
            /** Format: decimal */
            debris_deposit: string;
            /** Format: decimal */
            premium_total: string;
            /** Format: decimal */
            total_amount: string;
            non_binding: boolean;
        };
        HealthzResponse: {
            status: string;
        };
        LoginRequestRequest: {
            /** Format: email */
            email: string;
            username: string;
            password: string;
        };
        LoginResponse: {
            token_id: number;
            masked_email: string;
        };
        LogoutResponse: {
            status: string;
        };
        Me: {
            readonly id: number;
            /**
             * Email address
             * Format: email
             */
            readonly email: string;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            readonly username: string;
            readonly user_type: components["schemas"]["UserTypeEnum"];
            readonly is_mobile_verified: boolean;
        };
        MilestoneActionRequest: {
            action: components["schemas"]["ActionEnum"];
            /** @default  */
            decision_note: string;
            /** @default  */
            correction_reason: string;
        };
        MilestoneInstance: {
            readonly id: number;
            readonly application_number: string;
            readonly stream_code: string;
            readonly milestone_code: string;
            readonly sequence: number;
            readonly status: string;
            /** Format: date-time */
            readonly started_at: string;
            /** Format: date-time */
            readonly due_at: string;
            /** Format: date-time */
            readonly completed_at: string;
            readonly officer_remarks: string;
        };
        OfficerQueueItem: {
            readonly id: number;
            application_number: string;
            stream_code: string;
            stream_name: string;
            milestone_code: string;
            milestone_name: string;
            sequence: number;
            sla_working_days: number;
            status: string;
            /** Format: date-time */
            started_at: string;
            /** Format: date-time */
            due_at: string;
            document_count: number;
        };
        /**
         * @description * `applicant_raised` - Applicant Raised
         *     * `system_raised` - System Raised
         * @enum {string}
         */
        OriginEnum: "applicant_raised" | "system_raised";
        OtpResendRequest: {
            token_id: number;
        };
        OtpResendResponse: {
            token_id: number;
        };
        OtpVerifyRequest: {
            token_id: number;
            code: string;
        };
        OtpVerifyResponse: {
            status: string;
        };
        PatchedComplaintResolveRequest: {
            resolution_notes?: string;
        };
        PatchedConditionalClearanceFulfillRequest: {
            clearance_doc_id?: number;
        };
        PatchedPaymentVerifyRequest: {
            decision?: components["schemas"]["DecisionEnum"];
            /** Format: decimal */
            verified_amount?: string;
            /** @default  */
            remarks: string;
        };
        PaymentRead: {
            readonly id: number;
            challan_reference: string;
            /** Format: decimal */
            claimed_amount: string;
            /** Format: decimal */
            verified_amount?: string | null;
            status?: components["schemas"]["PaymentReadStatusEnum"];
            /** Format: date */
            payment_date: string;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            verified_at?: string | null;
            remarks?: string;
        };
        /**
         * @description * `claimed` - Claimed
         *     * `verified` - Verified
         *     * `rejected` - Rejected
         *     * `mismatch` - Amount Mismatch
         * @enum {string}
         */
        PaymentReadStatusEnum: "claimed" | "verified" | "rejected" | "mismatch";
        PaymentRecordRequest: {
            challan_reference: string;
            /** Format: decimal */
            claimed_amount: string;
            /** Format: date */
            payment_date: string;
        };
        PresignedUrlResponse: {
            /** Format: uri */
            url: string;
        };
        SignedPdfUploadRequest: {
            /** Format: binary */
            signed_pdf: string;
        };
        SignupRequest: {
            /** Format: email */
            email: string;
            username: string;
            password: string;
            full_name: string;
            aadhaar: string;
        };
        SignupResponse: {
            token_id: number;
        };
        StatusLookupResponse: {
            application_number: string;
            stream: string;
            stream_code: string;
            status: string;
            /** Format: date-time */
            submitted_at: string | null;
            milestones: components["schemas"]["StatusMilestoneItem"][];
        };
        StatusMilestoneItem: {
            code: string;
            name: string;
            sequence: number;
            status: string;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            completed_at: string | null;
            is_deemed: boolean;
        };
        StreamListItem: {
            id: number;
            code: string;
            name: string;
            description: string;
            milestones: components["schemas"]["StreamMilestoneItem"][];
        };
        StreamMilestoneItem: {
            code: string;
            name: string;
            sequence: number;
            sla_working_days: number;
            deemed_clearance_eligible: boolean;
        };
        /**
         * @description * `applicant` - Applicant
         *     * `officer` - Officer
         *     * `admin` - Admin
         * @enum {string}
         */
        UserTypeEnum: "applicant" | "officer" | "admin";
        _Certificate: {
            readonly id: number;
            certificate_type: components["schemas"]["CertificateTypeEnum"];
            certificate_number: string;
            signature_verified?: boolean;
            dsc_serial_used?: string;
            /** Format: date-time */
            readonly issued_at: string;
            /** Format: date */
            valid_until?: string | null;
            /** Format: date-time */
            revoked_at?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    applications_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"][];
                };
            };
        };
    };
    applications_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ApplicationCreateRequest"];
                "multipart/form-data": components["schemas"]["ApplicationCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
        };
    };
    applications_milestones_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MilestoneInstance"][];
                };
            };
        };
    };
    applications_milestones_action_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_number: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MilestoneActionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["MilestoneActionRequest"];
                "multipart/form-data": components["schemas"]["MilestoneActionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MilestoneInstance"];
                };
            };
        };
    };
    applications_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
        };
    };
    applications_submit_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationRead"];
                };
            };
        };
    };
    applications_status_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusLookupResponse"];
                };
            };
        };
    };
    applications_streams_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreamListItem"][];
                };
            };
        };
    };
    certificates_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_Certificate"][];
                };
            };
        };
    };
    certificates_download_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_number: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DownloadUrlResponse"];
                };
            };
        };
    };
    certificates_receive_signed_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_number: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["SignedPdfUploadRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["_Certificate"];
                };
            };
            /** @description No response body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    compliance_audit_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                target_id: number;
                target_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEvent"][];
                };
            };
        };
    };
    compliance_clearances_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionalClearanceRead"][];
                };
            };
        };
    };
    compliance_clearances_create_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_number: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConditionalClearanceCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ConditionalClearanceCreateRequest"];
                "multipart/form-data": components["schemas"]["ConditionalClearanceCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionalClearanceRead"];
                };
            };
        };
    };
    compliance_clearances_fulfill_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedConditionalClearanceFulfillRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedConditionalClearanceFulfillRequest"];
                "multipart/form-data": components["schemas"]["PatchedConditionalClearanceFulfillRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConditionalClearanceRead"];
                };
            };
        };
    };
    complaints_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintRead"][];
                };
            };
        };
    };
    compliance_complaints_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComplaintCreateRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ComplaintCreateRequest"];
                "multipart/form-data": components["schemas"]["ComplaintCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintRead"];
                };
            };
        };
    };
    complaints_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintRead"];
                };
            };
        };
    };
    compliance_complaints_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedComplaintResolveRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedComplaintResolveRequest"];
                "multipart/form-data": components["schemas"]["PatchedComplaintResolveRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComplaintRead"];
                };
            };
        };
    };
    csrf_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    documents_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadRead"];
                };
            };
        };
    };
    documents_presigned_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUrlResponse"];
                };
            };
        };
    };
    documents_slots_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                milestone_instance_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSlotRead"][];
                };
            };
        };
    };
    documents_upload_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["DocumentUploadCreateRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentUploadRead"];
                };
            };
        };
    };
    fees_assessment_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeAssessmentRead"];
                };
            };
        };
    };
    fees_assessment_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeAssessmentRead"];
                };
            };
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeAssessmentRead"];
                };
            };
        };
    };
    fees_payments_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_number: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRead"][];
                };
            };
        };
    };
    fees_payments_verify_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_number: string;
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPaymentVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPaymentVerifyRequest"];
                "multipart/form-data": components["schemas"]["PatchedPaymentVerifyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRead"];
                };
            };
        };
    };
    fees_payments_record_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                application_number: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRecordRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PaymentRecordRequest"];
                "multipart/form-data": components["schemas"]["PaymentRecordRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaymentRead"];
                };
            };
        };
    };
    fees_estimate_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeEstimateResponse"];
                };
            };
        };
    };
    healthz_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthzResponse"];
                };
            };
        };
    };
    identity_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequestRequest"];
                "multipart/form-data": components["schemas"]["LoginRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    identity_logout_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
        };
    };
    identity_me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    identity_otp_resend_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpResendRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OtpResendRequest"];
                "multipart/form-data": components["schemas"]["OtpResendRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpResendResponse"];
                };
            };
        };
    };
    identity_otp_verify_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerifyRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["OtpVerifyRequest"];
                "multipart/form-data": components["schemas"]["OtpVerifyRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OtpVerifyResponse"];
                };
            };
        };
    };
    identity_signup_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SignupRequest"];
                "multipart/form-data": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponse"];
                };
            };
        };
    };
    officer_queue_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OfficerQueueItem"][];
                };
            };
        };
    };
}
