# Generated by Django 5.2.3 on 2026-06-25 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("building_permission", "Building Permission Certificate"),
                            ("commencement", "Commencement Certificate"),
                            ("plinth", "Plinth Completion Certificate"),
                            ("oc", "Occupancy Certificate"),
                        ],
                        max_length=25,
                    ),
                ),
                ("certificate_number", models.CharField(max_length=30, unique=True)),
                ("r2_object_key", models.CharField(max_length=512)),
                ("signature_verified", models.BooleanField(default=False)),
                ("dsc_serial_used", models.CharField(blank=True, max_length=128)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("revocation_reason", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="certificates",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "db_table": "certificates_certificate",
            },
        ),
    ]
