# Generated by Django 5.2.3 on 2026-06-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("certificates", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="certificate",
            name="certificate_type",
            field=models.CharField(
                choices=[
                    ("aip", "Approval in Principle"),
                    ("development_permission", "Development Permission"),
                    ("commencement_plinth", "Commencement Certificate to Plinth"),
                    ("further_commencement", "Further Commencement Certificate"),
                    ("commencement_80pct", "Commencement Certificate (80% BUA)"),
                    ("commencement_rem20", "Commencement Certificate (Remaining 20%)"),
                    ("building_completion", "Building Completion Certificate"),
                    ("oc", "Occupancy Certificate"),
                    ("demolition_clearance", "Demolition & Site Clearance Certificate"),
                ],
                max_length=25,
            ),
        ),
    ]
