# Generated by Django 5.2.3 on 2026-06-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_number",
                    models.CharField(blank=True, db_index=True, max_length=20, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_scrutiny", "Under Scrutiny"),
                            ("awaiting_next_milestone", "Awaiting Next Milestone"),
                            ("rejected", "Rejected"),
                            ("approved", "Approved"),
                            ("expired", "Expired"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                (
                    "plpn",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Plot/Land Plan Number"
                    ),
                ),
                (
                    "plot_area_sqm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "proposed_bua_sqm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "existing_bua_sqm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "zonal_rrr",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
            ],
            options={
                "db_table": "applications_application",
            },
        ),
        migrations.CreateModel(
            name="ApplicationCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("prefix", models.CharField(default="MBPASPA", max_length=20)),
                ("next_value", models.PositiveIntegerField(default=1)),
            ],
            options={
                "db_table": "applications_counter",
            },
        ),
        migrations.CreateModel(
            name="ApplicationParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "party_role",
                    models.CharField(
                        choices=[
                            ("architect", "Architect"),
                            ("structural_engineer", "Structural Engineer"),
                            ("co_owner", "Co-Owner"),
                            ("legal_rep", "Legal Representative"),
                        ],
                        max_length=25,
                    ),
                ),
                ("is_account_of_record", models.BooleanField(default=False)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("mobile", models.CharField(blank=True, max_length=15)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "applications_party",
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "default_sla_working_days",
                    models.PositiveSmallIntegerField(default=21),
                ),
            ],
            options={
                "db_table": "applications_milestone",
            },
        ),
        migrations.CreateModel(
            name="MilestoneInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("deemed_cleared", "Deemed Cleared"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_deemed", models.BooleanField(default=False)),
                ("officer_remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "applications_milestone_instance",
            },
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "applications_stream",
            },
        ),
        migrations.CreateModel(
            name="StreamMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                ("deemed_clearance_eligible", models.BooleanField(default=True)),
                ("required_officer_role", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "db_table": "applications_stream_milestone",
                "ordering": ["stream", "sequence"],
            },
        ),
    ]
