# Generated by Django 5.2.3 on 2026-06-25 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("applications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="submitted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="submitted_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="applicationcounter",
            unique_together={("year", "prefix")},
        ),
        migrations.AddField(
            model_name="applicationparty",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parties",
                to="applications.application",
            ),
        ),
        migrations.AddField(
            model_name="applicationparty",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="application_parties",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="milestoneinstance",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestone_instances",
                to="applications.application",
            ),
        ),
        migrations.AddField(
            model_name="milestoneinstance",
            name="assigned_officer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_milestones",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="stream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="applications",
                to="applications.stream",
            ),
        ),
        migrations.AddField(
            model_name="streammilestone",
            name="milestone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stream_milestones",
                to="applications.milestone",
            ),
        ),
        migrations.AddField(
            model_name="streammilestone",
            name="stream",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stream_milestones",
                to="applications.stream",
            ),
        ),
        migrations.AddField(
            model_name="milestoneinstance",
            name="stream_milestone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="applications.streammilestone",
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(
                fields=["submitted_by", "status"], name="application_submitt_9737e7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="application",
            index=models.Index(fields=["stream", "status"], name="application_stream__cc5311_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="streammilestone",
            unique_together={("stream", "milestone"), ("stream", "sequence")},
        ),
        migrations.AddIndex(
            model_name="milestoneinstance",
            index=models.Index(
                fields=["application", "status"], name="application_applica_f6102f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="milestoneinstance",
            index=models.Index(
                fields=["assigned_officer", "status"],
                name="application_assigne_33cdb6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="milestoneinstance",
            index=models.Index(fields=["due_at"], name="application_due_at_508a0c_idx"),
        ),
    ]
