# Generated by Django 5.2.3 on 2026-06-25 11:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0003_streammilestone_safe_default"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="applicationparty",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_account_of_record", True)),
                fields=("application",),
                name="one_account_of_record_per_app",
            ),
        ),
    ]
