# Generated by Django 5.2.3 on 2026-06-25 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="documentupload",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="uploaded_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentslot",
            unique_together={("stream", "stream_milestone", "code")},
        ),
        migrations.AddIndex(
            model_name="documentupload",
            index=models.Index(
                fields=["application", "slot", "version"],
                name="documents_u_applica_bb2078_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documentupload",
            index=models.Index(fields=["status"], name="documents_u_status_b4321c_idx"),
        ),
    ]
