# Generated by Django 5.2.3 on 2026-06-25 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.CharField(max_length=500)),
                ("effective_from", models.DateField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "fees_config_parameter",
                "get_latest_by": "effective_from",
            },
        ),
        migrations.CreateModel(
            name="FeeAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scrutiny_fee", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "security_deposit",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "debris_deposit",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "premium_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("assessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bua_sqm_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "zonal_rrr_snapshot",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
            ],
            options={
                "db_table": "fees_assessment",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("challan_reference", models.CharField(db_index=True, max_length=100)),
                (
                    "claimed_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "verified_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("claimed", "Claimed"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("mismatch", "Amount Mismatch"),
                        ],
                        default="claimed",
                        max_length=10,
                    ),
                ),
                ("payment_date", models.DateField()),
                ("remarks", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "fees_payment",
            },
        ),
        migrations.CreateModel(
            name="Concession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "concession_type",
                    models.CharField(
                        choices=[
                            ("fsi", "FSI"),
                            ("open_space", "Open Space"),
                            ("parking", "Parking"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "detected_value",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "benchmark_value",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "premium_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("source", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="concessions",
                        to="applications.application",
                    ),
                ),
            ],
            options={
                "db_table": "fees_concession",
            },
        ),
    ]
