# Generated by Django 5.2.3 on 2026-06-25 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("applications", "0004_applicationparty_account_of_record_constraint"),
        ("fees", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="concession",
            name="detection_method",
            field=models.CharField(
                choices=[("auto", "Auto-detected"), ("declared", "Applicant-declared")],
                default="auto",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="feeassessment",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="feeassessment",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="feeassessment",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feeassessment",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_assessments",
                to="applications.application",
            ),
        ),
        migrations.AddConstraint(
            model_name="feeassessment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("application",),
                name="one_current_fee_assessment_per_app",
            ),
        ),
    ]
