# Generated by Django 5.2.3 on 2026-06-25 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verb", models.CharField(max_length=100)),
                ("target_type", models.CharField(max_length=100)),
                ("target_id", models.BigIntegerField()),
                ("payload", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "sequence",
                    models.BigIntegerField(editable=False, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "compliance_audit_event",
            },
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("applicant_raised", "Applicant Raised"),
                            ("system_raised", "System Raised"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_review", "In Review"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "compliance_complaint",
            },
        ),
        migrations.CreateModel(
            name="ConditionalClearance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "clearance_type",
                    models.CharField(
                        choices=[
                            ("noc", "No-Objection Certificate"),
                            ("structural", "Structural Stability"),
                            ("fire", "Fire Safety"),
                            ("environment", "Environmental Clearance"),
                            ("heritage", "Heritage Clearance"),
                            ("other", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField()),
                ("trigger_metadata", models.JSONField(default=dict)),
                ("is_fulfilled", models.BooleanField(default=False)),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "compliance_conditional_clearance",
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("description", models.CharField(max_length=200)),
                ("is_national", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "compliance_holiday",
                "ordering": ["date"],
            },
        ),
    ]
